[project]
name = "yorick-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "elevenlabs",
    "python-dotenv>=1.2.1",
]
